### ISSUE TITLE
Render overflow on logout

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/mobile-app#500]
### Describe the bug

A Render overflow is occurred, when a user logout out

### Describe how to produce the bug

Go to Profile and click the logout button

**Comment by AraxTheCoder** [comment]
I tried to reproduce the overflow error when logging out but instead of an overflow error i got an "Null check operator used on a null value" error which resulted in the short appearance of an error screen which looks identical to the one you would expect from an render overflow.

Is this the error you described?

```
The following _TypeError was thrown building Consumer<CurrentWardController>(dirty, dependencies:
[_InheritedProviderScope<CurrentWardController?>]):
Null check operator used on a null value

The relevant error-causing widget was:
  Consumer<CurrentWardController>
  Consumer:./mobile-app/apps/tasks/lib/components/user_bottom_sheet.dart:80:20

When the exception was thrown, this was the stack:
#0      _UserBottomSheetState.build.<anonymous closure>.<anonymous closure> (package:tasks/components/user_bottom_sheet.dart:84:103)
#1      Consumer.buildWithChild (package:provider/src/consumer.dart:179:19)
#2      SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
#4      SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#13     _invoke (dart:ui/hooks.dart:312:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#15     _drawFrame (dart:ui/hooks.dart:283:31)
```

**Comment by florian-sabonchi** [comment]
> I tried to reproduce the overflow error when logging out but instead of an overflow error i got an "Null check operator used on a null value" error which resulted in the short appearance of an error screen which looks identical to the one you would expect from an render overflow.
> 
> Is this the error you described?
> 
> ```
> The following _TypeError was thrown building Consumer<CurrentWardController>(dirty, dependencies:
> [_InheritedProviderScope<CurrentWardController?>]):
> Null check operator used on a null value
> 
> The relevant error-causing widget was:
>   Consumer<CurrentWardController>
>   Consumer:./mobile-app/apps/tasks/lib/components/user_bottom_sheet.dart:80:20
> 
> When the exception was thrown, this was the stack:
> #0      _UserBottomSheetState.build.<anonymous closure>.<anonymous closure> (package:tasks/components/user_bottom_sheet.dart:84:103)
> #1      Consumer.buildWithChild (package:provider/src/consumer.dart:179:19)
> #2      SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
> #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
> #4      SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
> #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
> #6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
> #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
> #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
> #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
> #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
> #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
> #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
> #13     _invoke (dart:ui/hooks.dart:312:13)
> #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
> #15     _drawFrame (dart:ui/hooks.dart:283:31)
> ```

Yes, thats the error i described i think we should rename
